stages:
  - build
  - test

.windows-x86_64-build-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_normal
    - cd build_normal
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DENABLE_UNITYBUILD=OFF
    - cd ..
    - mkdir build_unity
    - cd build_unity
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_normal --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_normal --target ALL_BUILD --config Debug --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Debug --parallel 16
    - echo "Compile complete."
    - mkdir windows-x86_64
    - copy build_unity/tests/Release/test_Sys.exe windows-x86_64
    - copy build_unity/tests/Debug/test_Sys-dbg.exe windows-x86_64
  artifacts:
    name: windows-x86_64
    paths:
      - windows-x86_64/
    expire_in: 1 week

.windows-arm64-build-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_normal
    - cd build_normal
    - cmake .. -G "Visual Studio 17 2022" -A ARM64 -DENABLE_UNITYBUILD=OFF
    - cd ..
    - mkdir build_unity
    - cd build_unity
    - cmake .. -G "Visual Studio 17 2022" -A ARM64 -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build_normal --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_normal --target ALL_BUILD --config Debug --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Debug --parallel 16
    - echo "Compile complete."
    - mkdir windows-arm64
    - copy build_unity/tests/Release/test_Sys.exe windows-arm64
    - copy build_unity/tests/Debug/test_Sys-dbg.exe windows-arm64
  artifacts:
    name: windows-arm64
    paths:
      - windows-arm64/
    expire_in: 1 week

.linux-build-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_UNITYBUILD=ON
    - cd ..
    - mkdir build_dbg
    - cd build_dbg
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build --target all --parallel 16
    - cmake --build build_dbg --target all --parallel 16
    - echo "Compile complete."
    - mkdir linux-x86_64
    - cp build/tests/test_Sys linux-x86_64
    - cp build_dbg/tests/test_Sys-dbg linux-x86_64
  artifacts:
    paths:
      - linux-x86_64/
    expire_in: 1 week

.macos-x86_64-build-job:
  stage: build
  tags:
    - macos
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_APPLE_SILICON_PROCESSOR=x86_64 -DCMAKE_BUILD_TYPE=Release -DENABLE_UNITYBUILD=ON
    - cd ..
    - mkdir build_dbg
    - cd build_dbg
    - cmake .. -DCMAKE_APPLE_SILICON_PROCESSOR=x86_64 -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build --target all --parallel 16
    - cmake --build build_dbg --target all --parallel 16
    - echo "Compile complete."
    - mkdir macos-x86_64
    - cp build/tests/test_Sys macos-x86_64
    - cp build_dbg/tests/test_Sys-dbg macos-x86_64
  artifacts:
    paths:
      - macos-x86_64/
    expire_in: 1 week

.macos-arm64-build-job:
  stage: build
  tags:
    - macos
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_APPLE_SILICON_PROCESSOR=arm64 -DCMAKE_BUILD_TYPE=Release -DENABLE_UNITYBUILD=ON
    - cd ..
    - mkdir build_dbg
    - cd build_dbg
    - cmake .. -DCMAKE_APPLE_SILICON_PROCESSOR=arm64 -DCMAKE_BUILD_TYPE=Debug -DENABLE_UNITYBUILD=ON
    - cd ..
    - cmake --build build --target all --parallel 16
    - cmake --build build_dbg --target all --parallel 16
    - echo "Compile complete."
    - mkdir macos-arm64
    - cp build/tests/test_Sys macos-arm64
    - cp build_dbg/tests/test_Sys-dbg macos-arm64
  artifacts:
    paths:
      - macos-arm64/
    expire_in: 1 week

.windows-test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd tests
    - '& "../$BIN_DIR/test_Sys-dbg"'
    - cd ../

.test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd tests
    - ../$BIN_DIR/test_Sys
    - cd ../

windows-x86_64-build-job:
  extends:
    - .windows-x86_64-build-job
  tags:
    - windows

windows-arm64-build-job:
  extends:
    - .windows-arm64-build-job
  tags:
    - windows

linux-x86_64-build-job:
  extends:
    - .linux-build-job
  tags:
    - linux

macos-x86_64-build-job:
  extends:
    - .macos-x86_64-build-job
  tags:
    - macos

macos-arm64-build-job:
  extends:
    - .macos-arm64-build-job
  tags:
    - macos

windows-x86_64-cpu-test-job:
  variables:
    BIN_DIR: windows-x86_64
  extends:
    - .windows-test-job
  needs:
    - windows-x86_64-build-job
  tags:
    - windows,x86_64

windows-arm64-cpu-test-job:
  variables:
    BIN_DIR: windows-arm64
  extends:
    - .windows-test-job
  needs:
    - windows-arm64-build-job
  tags:
    - windows,arm64

linux-x86_64-cpu-test-job:
  variables:
    BIN_DIR: linux-x86_64
  extends:
    - .test-job
  needs:
    - linux-x86_64-build-job
  tags:
    - linux,x86_64

macos-x86_64-cpu-test-job:
  variables:
    BIN_DIR: macos-x86_64
  extends:
    - .test-job
  needs:
    - macos-x86_64-build-job
  tags:
    - macos,x86_64

macos-arm64-cpu-test-job:
  variables:
    BIN_DIR: macos-arm64
  extends:
    - .test-job
  needs:
    - macos-arm64-build-job
  tags:
    - macos,arm64

