name: CI

on:
  pull_request:
    branches:
      - 'releases/**'

jobs:
  build-windows-x86_64-gl-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-gl
          path: windows-x86_64-gl/
  build-windows-x86_64-gl-dbg:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL"
          config: "Debug"
  build-windows-x86_64-gl-dev:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=GL"
          config: "RelWithDebInfo"
  build-windows-x86_64-vk-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-vk
          path: windows-x86_64-vk/
  build-windows-x86_64-vk-dbg:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK"
          config: "Debug"
  build-windows-x86_64-vk-dev:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows-ninja
        with:
          cmake-args: "-DRENDERER=VK"
          config: "RelWithDebInfo"
  build-linux-x86_64-gl-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-gl
          path: linux-x86_64-gl/
  build-linux-x86_64-gl-dbg:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL"
          config: "Debug"
  build-linux-x86_64-gl-dev:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=GL"
          config: "RelWithDebInfo"
  build-linux-x86_64-vk-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-vk
          path: linux-x86_64-vk/
  build-linux-x86_64-vk-dbg:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK"
          config: "Debug"
  build-linux-x86_64-vk-dev:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK"
          config: "RelWithDebInfo"
  build-linux-x86_64-vk-tsan:
    runs-on: [ linux, builder ]
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DRENDERER=VK"
          config: "Tsan"
          bin-dir: "linux-x86_64-vk-tsan"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-vk-tsan
          path: linux-x86_64-vk-tsan/
  build-macos-x86_64-vk-rel:
    runs-on: [ macos, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON -DCMAKE_APPLE_SILICON_PROCESSOR=x86_64"
          config: "Release"
          bin-dir: "macos-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-x86_64-vk
          path: macos-x86_64-vk/
  build-macos-x86_64-vk-dbg:
    runs-on: [ macos, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON -DCMAKE_APPLE_SILICON_PROCESSOR=x86_64"
          config: "Debug"
  build-macos-x86_64-vk-dev:
    runs-on: [ macos, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-macos
        with:
          cmake-args: "-DRENDERER=VK -DCMAKE_UNITY_BUILD=ON -DCMAKE_APPLE_SILICON_PROCESSOR=x86_64"
          config: "RelWithDebInfo"
  # build-windows-x86_64-vk-asan:
  #   runs-on: [ windows, builder ]
  #   steps:
  #     - name: Checkout Workflows
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Re-initialize repository
  #       uses: ./.github/actions/checkout
  #     - name: Compile the code
  #       uses: ./.github/actions/build-windows
  #       with:
  #         cmake-args: "-A x64 -DRENDERER=VK"
  #         config: "Asan"
  #         bin-dir: "windows-x86_64-vk-asan"
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: windows-x86_64-vk-asan
  #         path: windows-x86_64-vk-asan/
  test-windows-x86_64-vk-amd:
    runs-on: [ windows, x86_64, amd ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          out-dir: "windows-x86_64-vk-amd-output"
          test-args: "-j2 --device AMD --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-vk-amd-output
          path: windows-x86_64-vk-amd-output/
  test-windows-x86_64-vk-nv:
    runs-on: [ windows, x86_64, nv ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          out-dir: "windows-x86_64-vk-nv-output"
          test-args: "-j2 --device NV --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-vk-nv-output
          path: windows-x86_64-vk-nv-output/
  test-windows-x86_64-vk-arc:
    runs-on: [ windows, x86_64, arc ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          out-dir: "windows-x86_64-vk-arc-output"
          test-args: "-j2 --device Arc --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-vk-arc-output
          path: windows-x86_64-vk-arc-output/
  test-windows-x86_64-vk-xe:
    runs-on: [ windows, x86_64, xe ]
    needs:
      - build-windows-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-vk"
          out-dir: "windows-x86_64-vk-xe-output"
          test-args: "-j2 --device Xe  --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-vk-xe-output
          path: windows-x86_64-vk-xe-output/
  test-windows-x86_64-gl-nv:
    runs-on: [ windows, x86_64, nv ]
    needs:
      - build-windows-x86_64-gl-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-gl"
          out-dir: "windows-x86_64-gl-nv-output"
          test-args: "-j2 --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-gl-nv-output
          path: windows-x86_64-gl-nv-output/
  test-windows-x86_64-gl-arc:
    runs-on: [ windows, x86_64, arc ]
    needs:
      - build-windows-x86_64-gl-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "windows-x86_64-gl"
          out-dir: "windows-x86_64-gl-arc-output"
          test-args: "-j2 -vl 0 --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-x86_64-gl-arc-output
          path: windows-x86_64-gl-arc-output/
  test-linux-x86_64-vk-amd:
    runs-on: [ linux, x86_64, amd ]
    needs:
      - build-linux-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-vk"
          out-dir: "linux-x86_64-vk-amd-output"
          test-args: "-j2 --device AMD --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: linux-x86_64-vk-amd-output
          path: linux-x86_64-vk-amd-output/
  test-linux-x86_64-vk-nv:
    runs-on: [ linux, x86_64, nv ]
    needs:
      - build-linux-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-vk"
          out-dir: "linux-x86_64-vk-nv-output"
          test-args: "-j2 --device NV --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: linux-x86_64-vk-nv-output
          path: linux-x86_64-vk-nv-output/
  test-linux-x86_64-gl-nv:
    runs-on: [ linux, x86_64, nv ]
    needs:
      - build-linux-x86_64-gl-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-gl"
          out-dir: "linux-x86_64-gl-nv-output"
          test-args: "-j2 --device NV --full"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: linux-x86_64-gl-nv-output
          path: linux-x86_64-gl-nv-output/
  # test-windows-x86_64-vk-asan:
  #   runs-on: [ windows, x86_64 ]
  #   needs:
  #     - build-windows-x86_64-vk-asan
  #   steps:
  #     - name: Checkout Workflows
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Re-initialize repository
  #       uses: ./.github/actions/checkout
  #     - name: Run Tests
  #       uses: ./.github/actions/test-asan
  #       with:
  #         bin-dir: "windows-x86_64-vk-asan"
  #         test-args: "-j4"
  # test-linux-x86_64-vk-tsan:
  #   runs-on: [ linux, x86_64 ]
  #   needs:
  #     - build-linux-x86_64-vk-tsan
  #   steps:
  #     - name: Checkout Workflows
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Re-initialize repository
  #       uses: ./.github/actions/checkout
  #     - name: Run Tests
  #       uses: ./.github/actions/test-tsan
  #       with:
  #         bin-dir: "linux-x86_64-vk-tsan"
  #         test-args: "-j2"
  analyze-output:
    runs-on: [ linux ]
    needs: [ test-windows-x86_64-vk-amd, test-windows-x86_64-vk-nv, test-windows-x86_64-gl-nv, test-windows-x86_64-vk-arc, test-windows-x86_64-vk-xe, test-windows-x86_64-gl-arc, test-linux-x86_64-vk-amd, test-linux-x86_64-vk-nv, test-linux-x86_64-gl-nv ]
    if: always()
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: scripts/analyze_output.py
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-vk-nv-output
          path: windows-x86_64-vk-nv-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-gl-nv-output
          path: windows-x86_64-gl-nv-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-vk-amd-output
          path: windows-x86_64-vk-amd-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-vk-arc-output
          path: windows-x86_64-vk-arc-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-vk-xe-output
          path: windows-x86_64-vk-xe-output/
      - uses: actions/download-artifact@v3
        with:
          name: windows-x86_64-gl-arc-output
          path: windows-x86_64-gl-arc-output/
      - uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-vk-amd-output
          path: linux-x86_64-vk-amd-output/
      - uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-vk-nv-output
          path: linux-x86_64-vk-nv-output/
      - uses: actions/download-artifact@v3
        with:
          name: linux-x86_64-gl-nv-output
          path: linux-x86_64-gl-nv-output/
      - name: Analyze Output
        run: |
          python scripts/analyze_output.py windows-x86_64-vk-nv-output/test_Eng_output.txt windows-x86_64-vk-amd-output/test_Eng_output.txt windows-x86_64-vk-arc-output/test_Eng_output.txt windows-x86_64-vk-xe-output/test_Eng_output.txt windows-x86_64-gl-arc-output/test_Eng_output.txt linux-x86_64-vk-nv-output/test_Eng_output.txt linux-x86_64-gl-nv-output/test_Eng_output.txt linux-x86_64-vk-amd-output/test_Eng_output.txt
        shell: bash