stages:
  - build
  - test

.windows-x86_64-build-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_normal
    - cd build_normal
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_UNITY_BUILD=OFF
    - cd ..
    - mkdir build_unity
    - cd build_unity
    - cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_UNITY_BUILD=ON
    - cd ..
    - cmake --build build_normal --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_normal --target ALL_BUILD --config Asan --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Asan --parallel 16
    - echo "Compile complete."
    - mkdir windows-x86_64
    - copy build_unity/tests/Release/test_Net.exe windows-x86_64
    - copy build_unity/tests/Asan/test_Net-asan.exe windows-x86_64
  artifacts:
    name: windows-x86_64
    paths:
      - windows-x86_64/
    expire_in: 1 week

.windows-arm64-build-job:
  stage: build
  tags:
    - windows
  script:
    - echo "Compiling the code..."
    - mkdir build_normal
    - cd build_normal
    - cmake .. -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_UNITY_BUILD=OFF
    - cd ..
    - mkdir build_unity
    - cd build_unity
    - cmake .. -G "Visual Studio 17 2022" -A ARM64 -DCMAKE_UNITY_BUILD=ON
    - cd ..
    - cmake --build build_normal --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_normal --target ALL_BUILD --config Asan --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Release --parallel 16
    - cmake --build build_unity --target ALL_BUILD --config Asan --parallel 16
    - echo "Compile complete."
    - mkdir windows-arm64
    - copy build_unity/tests/Release/test_Net.exe windows-arm64
    - copy build_unity/tests/Asan/test_Net-asan.exe windows-arm64
  artifacts:
    name: windows-arm64
    paths:
      - windows-arm64/
    expire_in: 1 week

.linux-build-job:
  stage: build
  tags:
    - linux
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON
    - cd ..
    - mkdir build_dbg
    - cd build_dbg
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_UNITY_BUILD=ON
    - cd ..
    - cmake --build build --target all --parallel 16
    - cmake --build build_dbg --target all --parallel 16
    - echo "Compile complete."
    - mkdir linux-x86_64
    - cp build/tests/test_Net linux-x86_64
    - cp build_dbg/tests/test_Net-dbg linux-x86_64
  artifacts:
    paths:
      - linux-x86_64/
    expire_in: 1 week

.macos-universal-build-job:
  stage: build
  tags:
    - macos
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_UNITY_BUILD=ON
    - cd ..
    - mkdir build_dbg
    - cd build_dbg
    - cmake .. -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_UNITY_BUILD=ON
    - cd ..
    - cmake --build build --target all --parallel 16
    - cmake --build build_dbg --target all --parallel 16
    - echo "Compile complete."
    - mkdir macos-universal
    - cp build/tests/test_Net macos-universal
    - cp build_dbg/tests/test_Net-dbg macos-universal
  artifacts:
    paths:
      - macos-universal/
    expire_in: 1 week

.windows-test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd tests
    - '& "../$BIN_DIR/test_Net-asan"'
    - cd ../

.test-job:
  stage: test
  script:
    - echo "Running tests..."
    - cd tests
    - ../$BIN_DIR/test_Net
    - cd ../

windows-x86_64-build-job:
  extends:
    - .windows-x86_64-build-job
  tags:
    - windows

windows-arm64-build-job:
  extends:
    - .windows-arm64-build-job
  tags:
    - windows

linux-x86_64-build-job:
  extends:
    - .linux-build-job
  tags:
    - linux

macos-universal-build-job:
  extends:
    - .macos-universal-build-job
  tags:
    - macos

windows-x86_64-test-job:
  variables:
    BIN_DIR: windows-x86_64
  extends:
    - .windows-test-job
  needs:
    - windows-x86_64-build-job
  tags:
    - windows,x86_64

windows-arm64-test-job:
  variables:
    BIN_DIR: windows-arm64
  extends:
    - .windows-test-job
  needs:
    - windows-arm64-build-job
  tags:
    - windows,arm64

linux-x86_64-test-job:
  variables:
    BIN_DIR: linux-x86_64
  extends:
    - .test-job
  needs:
    - linux-x86_64-build-job
  tags:
    - linux,x86_64

macos-x86_64-test-job:
  variables:
    BIN_DIR: macos-universal
  extends:
    - .test-job
  needs:
    - macos-universal-build-job
  tags:
    - macos,x86_64

macos-arm64-test-job:
  variables:
    BIN_DIR: macos-universal
  extends:
    - .test-job
  needs:
    - macos-universal-build-job
  tags:
    - macos,arm64
